export enum NodeKind {
  PROGRAM = 'PROGRAM',

  // Statements
  LET_STATEMENT = 'LET_STATEMENT',
  CONST_STATEMENT = 'CONST_STATEMENT',
  RETURN_STATEMENT = 'RETURN_STATEMENT',
  ASSIGN_STATEMENT = 'ASSIGN_STATEMENT',
  EXPRESSION_STATEMENT = 'EXPRESSION_STATEMENT',
  BLOCK_STATEMENT = 'BLOCK_STATEMENT',
  FUNCTION_DECLARATION = 'FUNCTION_DECLARATION',

  // Expressions
  IDENTIFIER = 'IDENTIFIER',
  NUMBER_LITERAL = 'NUMBER_LITERAL',
  BOOLEAN_LITERAL = 'BOOLEAN_LITERAL',
  STRING_LITERAL = 'STRING_LITERAL',
  CHARACTER_LITERAL = 'CHARACTER_LITERAL',
  NIL_LITERAL = 'NIL_LITERAL',
  ARRAY_LITERAL = 'ARRAY_LITERAL',

  PREFIX_EXPRESSION = 'PREFIX_EXPRESSION',
  INFIX_EXPRESSION = 'INFIX_EXPRESSION',
  IF_EXPRESSION = 'IF_EXPRESSION',
  WHILE_EXPRESSION = 'WHILE_EXPRESSION',
  CALL_EXPRESSION = 'CALL_EXPRESSION',
}

export interface Node {
  kind: NodeKind;
  tokenLiteral(): string;
}

export interface Statement extends Node {}

export interface Expression extends Node {}
